---
name: Build and publish CV

on:
  workflow_dispatch: {}
  push:
    branches: main
    paths:
      - 'cv/*.tex'

permissions:
  contents: write

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/soerenschneider/pdflatex

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build pdf
        run: |
          cd cv
          pdflatex *.tex

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "cv/*.pdf"
          tag_name: cv
